name: Pass Data Between Jobs

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.result.outputs.date }} # Reference the date from the step below
    steps:
      - name: Generate output
        id: result
        run: echo "date=$(date +%s)" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1 # Indicates the jobs to run sequentially. By default run in parallel.
    steps:
      - name: Use output from Job 1
        run: "echo 'Output from Job 1: ${{ needs.job1.outputs.result }}'"
